name: Close Issue

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  

jobs:
   close-issues:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: close-issue
      id: closeIssue
      uses: ./.github/actions/closeissue
      env:
        GithubRepository: ${{ github.repository }}
        GithubToken: ${{ secrets.GITHUB_TOKEN }}


