name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8-20 * * 1-5
  

jobs:
   publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: close-issue
      id: closeIssue
      uses: ./.github/actions/publish
      env:
        GithubRepository: ${{ github.repository }}
        GithubToken: ${{ secrets.GITHUB_TOKEN }}
        TwitterConsumerKey: ${{ secrets.TWITTERCONSUMERKEY }}
        TwitterConsumerSecret: ${{ secrets.TWITTERCONSUMERSECRET }}
        TwitterAccessTokenKey: ${{ secrets.TWITTERACCESSTOKENKEY }}
        TwitterAccessTokenSecret: ${{ secrets.TWITTERACCESSTOKENSECRET }}
        BlueSkyAppNameCode: ${{ secrets.BLUESKY_APPNAME_CODE }}
        BlueSkyHandle: ${{ secrets.BLUESKY_HANDLE }}
        

