name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8-20 * * 1-5
  

jobs:
   publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: close-issue
      id: closeIssue
      uses: ./.github/actions/publish
      env:
        GithubRepository: ${{ github.repository }}
        GithubToken: ${{ secrets.GITHUB_TOKEN }}
        TwitterConsumerKey: ${{ secrets.TWITTERCONSUMERKEY }}
        TwitterConsumerSecret: ${{ secrets.TWITTERCONSUMERSECRET }}
        TwitterAccessTokenKey: ${{ secrets.TWITTERACCESSTOKENKEY }}
        TwitterAccessTokenSecret: ${{ secrets.TWITTERACCESSTOKENSECRET }}


    - name: push-update
      run: |
        ls -R
        git config --global user.name 'Gitub Action Bot'
        git config --global user.email 'wilfried.woivre@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am "Read RSS items"
        git pull --rebase
        git push
