name: Test

on:
  workflow_dispatch:
  

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-builder.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3

    - name: debug
      run: echo $GITHUB_OUTPUT

    - name: matrix-builder
    id: matrix-builder
    uses: ./.github/actions/build-matrix

    - name: debug post
      run: cat $GITHUB_OUTPUT

  test:
    needs:
      - generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: debug
        run: echo $FeedName ($FeedLink) $AutoPublish
        env:
          FeedName: ${{ matrix.FeedName }}
          FeedLink: ${{ matrix.FeedLink }}
          AutoPublish: ${{ matrix.AutoPublish }}
