name: Test

on:
  workflow_dispatch:
  

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix-builder.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3

    - name: debug
    - run: $GITHUB_OUTPUT
    